# Typos configuration file
#
# Info:    https://github.com/marketplace/actions/typos-action
# Install: brew install typos-cli
# Install: conda install typos
# Run:     typos -c .github/_typos.toml

[files]
extend-exclude = [
    "_typos.toml",
    "docs/xmldocs/",
    "samples/LLama.Web/wwwroot/",
    "src/LLama/runtimes/deps/",
    "test/LLama.Benchmark/Assets/",
    "samples/LLama.Examples/Assets/"
]
